[tool.poetry]
name = "haige"
version = "0.1.0"
description = "依赖管理"
authors = ["lianhaifeng"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
